ARCH := $(shell arch)
CONDA_EXE ?= {{ cookiecutter.conda_path }}
MODULE_NAME := {{ cookiecutter.module_name }}
PROFILE = {{ cookiecutter.aws_profile }}
PROJECT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
PROJECT_NAME := {{ cookiecutter.repo_name }}
PYTHON_INTERPRETER := {{ cookiecutter.python_interpreter }}
VIRTUALENV := {{ cookiecutter.virtualenv }}
