ARCH := $(shell arch)
CONDA_EXE ?= {{ cookiecutter.conda_path }}
MODULE_NAME := {{ cookiecutter.module_name }}
TESTS_NO_CI = $(MODULE_NAME)/tests/no_ci
PROJECT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
PROJECT_NAME := {{ cookiecutter.repo_name }}
PYTHON_INTERPRETER := python3
VIRTUALENV := {{ cookiecutter.virtualenv }}
